language: cpp

matrix:
  include:
  - os: osx
    name: "Build"
    osx_image: xcode10.2
    compiler: clang

    script:
      - git clone https://github.com/acidanthera/MacKernelSDK
      - src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - xcodebuild -configuration Debug
      - xcodebuild -jobs 1 -configuration Release

    deploy:
      provider: releases
      skip_cleanup: true
      file: "build/*/*.zip"
      file_glob: true
      api_key:
        secure: M68OrYwLI5Nfqp1SLWv9Mc7Ru60l2RALu6ibF1fVQplBs1ZvzADHbKXtEOboDtoxg/rpBubmlm67B5daEJuTUuskZrymjXnolnRIZE5kNcTim8JM/xJ3cYAQnlQZW3Z5Lxc3qi2tZEsw1WvCK93RETZaCVnariBTJismj03tRd142k4alOfUfq+bsuxEzsCDapmrtXBrw6I0jcYOV6dwfIkRjQGt3up41eIMINmmsk1PKPrFB+rw2dDV4jYXxkLuMHps9mYM6flB3+PPWXlct15xtYMSn0okmQ336hrkKzrx/JFiMHru4KM2cTZ1hG8O0Q81XLSUyJ4vIZtmWNPbXstKW7RKJwm1j4tfFolaSacMlwGiuzR+WoCd++tsEm5fprutWocIZ34qMFQ9sVtiaeCuKPobzBed9Rvvjbk+e1KVaUaQfuMwQsM92Yuy/BRS8l11tgzfQQNEYrqhRuaaNqSmenDoWjj21ADIhMNWk7wz0yTKBlm6nI1hwxVcW5mAuAbNzqkJdePVwjrG6CqyZhjSRjGkxp51e7cXKhygNeVeCn84LIzaouzci668YZ5rjuXDx6ucH35GdqXZ076MWmqG6+qEV9VG41XzOoh95BjvvJKTzfDsmtkKfSw2IN6cOeCdzRkJ3fHfo2Ezib9vgj3ziCNK0A4kU7Gg+JRIF7s=
      on:
        tags: true
  - os: osx
    name: "Analyze Clang"
    osx_image: xcode11
    compiler: clang

    script:
      - git clone https://github.com/acidanthera/MacKernelSDK
      - src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - xcodebuild analyze -quiet -scheme NVMeFix -configuration Debug CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]
      - xcodebuild analyze -quiet -scheme NVMeFix -configuration Release CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]
